### ISSUE TITLE
No Releases yet

### ISSUE THREAD

**Issue by PetrDvoracek** [ArtemKirsanov/BlenderBrain#1]
The documentation says _Download the latest BlenderBrain.zip from the Releases section_, but there are no releases yet. How to install the add-on to blender without release? When I download the repository itself and try to install it to the blender, I can not find the **Add Mesh: BlenderBrain** add-on to enable it.

Thank you!

**Comment by ArtemKirsanov** [comment]
Whoops, it looks like I created the zip file locally on my machine by forgot to add that as a public release. Thank you so much for pointing it out!
Resolved

**Comment by ArtemKirsanov** [comment]
Whoops, it looks like I created the zip file locally on my machine by forgot to add that as a public release. Thank you so much for pointing it out!
Resolved
